connector:
    name: oro_importexport
    jobs:
        zendesk_user_import:
            title: "Sync users from Zendesk"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_zendesk.zendesk.user_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        zendesk_ticket_import:
            title: "Sync tickets from Zendesk"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_zendesk.zendesk.ticket_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        zendesk_ticket_export:
            title: "Sync tickets to Zendesk"
            type:  export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    oro_integration.reader.entity.by_id
                        processor: oro_importexport.processor.export_delegate
                        writer:    orocrm_zendesk.importexport.writer.ticket_export
                    parameters:
                        batch_size: 25

        zendesk_ticket_comment_import:
            title: "Sync ticket comments from Zendesk"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_zendesk.zendesk.ticket_comment_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25

        zendesk_ticket_comment_export:
            title: "Sync ticket comments to Zendesk"
            type:  export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    oro_integration.reader.entity.by_id
                        processor: oro_importexport.processor.export_delegate
                        writer:    orocrm_zendesk.importexport.writer.ticket_comment_export
                    parameters:
                        batch_size: 25
