parameters:
    orocrm_zendesk.importexport.reader.zendesk_api.class:   OroCRM\Bundle\ZendeskBundle\ImportExport\Reader\ZendeskAPIReader
    orocrm_zendesk.importexport.reader.ticket_reader.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Reader\TicketReader

    orocrm_zendesk.importexport.normalizer.user.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Serializer\Normalizer\UserNormalizer
    orocrm_zendesk.importexport.normalizer.user_role.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Serializer\Normalizer\UserRoleNormalizer
    orocrm_zendesk.importexport.normalizer.ticket.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Serializer\Normalizer\TicketNormalizer
    orocrm_zendesk.importexport.normalizer.ticket_status.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Serializer\Normalizer\TicketStatusNormalizer
    orocrm_zendesk.importexport.normalizer.ticket_priority.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Serializer\Normalizer\TicketPriorityNormalizer
    orocrm_zendesk.importexport.normalizer.ticket_type.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Serializer\Normalizer\TicketTypeNormalizer

    orocrm_zendesk.importexport.strategy.abstract_sync.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Strategy\AbstractSyncStrategy
    orocrm_zendesk.importexport.strategy.user_sync.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Strategy\UserSyncStrategy
    orocrm_zendesk.importexport.strategy.ticket_sync.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Strategy\TicketSyncStrategy

    orocrm_zendesk.importexport.provider.oro_entity.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Strategy\Provider\OroEntityProvider
    orocrm_zendesk.importexport.provider.zendesk_entity.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Strategy\Provider\ZendeskEntityProvider

services:
    # Readers
    orocrm_zendesk.importexport.reader.zendesk_api:
        class: %orocrm_zendesk.importexport.reader.zendesk_api.class%
        arguments:
          - @oro_importexport.context_registry
          - @orocrm_zendesk.rest_client_factory

    orocrm_zendesk.importexport.reader.ticket_reader:
        parent: orocrm_zendesk.importexport.reader.zendesk_api
        class: %orocrm_zendesk.importexport.reader.ticket_reader.class%

    # Processors
    orocrm_zendesk.importexport.processor.user_sync:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setStrategy, [@orocrm_zendesk.importexport.strategy.user_sync]]
        tags:
            -
              name: oro_importexport.processor
              type: import
              entity: %orocrm_zendesk.entity.user.class%
              alias: orocrm_zendesk.sync_from_zendesk_user

    orocrm_zendesk.importexport.processor.ticket_sync:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setStrategy, [@orocrm_zendesk.importexport.strategy.ticket_sync]]
        tags:
            -
              name: oro_importexport.processor
              type: import
              entity: %orocrm_zendesk.entity.ticket.class%
              alias: orocrm_zendesk.sync_from_zendesk_ticket

    # Normalizers
    orocrm_zendesk.importexport.normalizer.user:
        class: %orocrm_zendesk.importexport.normalizer.user.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_zendesk.importexport.normalizer.user_role:
        class: %orocrm_zendesk.importexport.normalizer.user_role.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_zendesk.importexport.normalizer.ticket:
        class: %orocrm_zendesk.importexport.normalizer.ticket.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_zendesk.importexport.normalizer.ticket_status:
        class: %orocrm_zendesk.importexport.normalizer.ticket_status.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_zendesk.importexport.normalizer.ticket_priority:
        class: %orocrm_zendesk.importexport.normalizer.ticket_priority.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_zendesk.importexport.normalizer.ticket_type:
        class: %orocrm_zendesk.importexport.normalizer.ticket_type.class%
        tags:
            - { name: oro_importexport.normalizer }

    # Strategies
    orocrm_zendesk.importexport.strategy.abstract_sync:
        class: %orocrm_zendesk.importexport.strategy.abstract_sync.class%
        abstract: true
        calls:
             - [setEntityManager, [@doctrine.orm.entity_manager]]
             - [setZendeskProvider, [@orocrm_zendesk.importexport.provider.zendesk_entity]]

    orocrm_zendesk.importexport.strategy.user_sync:
        class: %orocrm_zendesk.importexport.strategy.user_sync.class%
        parent: orocrm_zendesk.importexport.strategy.abstract_sync
        arguments:
            - @orocrm_zendesk.importexport.provider.oro_entity

    orocrm_zendesk.importexport.strategy.ticket_sync:
        class: %orocrm_zendesk.importexport.strategy.ticket_sync.class%
        parent: orocrm_zendesk.importexport.strategy.abstract_sync
        arguments:
            - @orocrm_case.manager
            - @orocrm_zendesk.entity_mapper
            - @orocrm_zendesk.importexport.provider.oro_entity

    # Providers
    orocrm_zendesk.importexport.provider.oro_entity:
        class: %orocrm_zendesk.importexport.provider.oro_entity.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @orocrm_zendesk.configuration_provider

    orocrm_zendesk.importexport.provider.zendesk_entity:
        class: %orocrm_zendesk.importexport.provider.zendesk_entity.class%
        arguments:
            - @doctrine.orm.entity_manager
