parameters:
    orocrm_zendesk.importexport.reader.zendesk_api.class: OroCRM\Bundle\ZendeskBundle\ImportExport\ZendeskAPIReader
    orocrm_zendesk.importexport.normalizer.user.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Serializer\Normalizer\UserNormalizer
    orocrm_zendesk.importexport.normalizer.user_role.class: OroCRM\Bundle\ZendeskBundle\ImportExport\Serializer\Normalizer\UserRoleNormalizer

services:
    orocrm_zendesk.importexport.reader.zendesk_api:
        class: %orocrm_zendesk.importexport.reader.zendesk_api.class%
        arguments:
          - @oro_importexport.context_registry
          - @orocrm_zendesk.rest_client_factory

    orocrm_zendesk.importexport.processor.zendesk_user_sync:
        parent: oro_importexport.processor.import_abstract
#        calls:
#             - [setDataConverter, [@orocrm_contact.importexport.data_converter.contact]]
#             - [setStrategy, [@orocrm_contact.importexport.strategy.import.contact.add_or_replace]]
        tags:
            -
              name: oro_importexport.processor
              type: import
              entity: %orocrm_zendesk.entity.user.class%
              alias: orocrm_zendesk.sync_from_zendesk_user

    # Normalizers
    orocrm_zendesk.importexport.normalizer.user:
        class: %orocrm_zendesk.importexport.normalizer.user.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_zendesk.importexport.normalizer.user_role:
        class: %orocrm_zendesk.importexport.normalizer.user_role.class%
        tags:
            - { name: oro_importexport.normalizer }
