placeholders:
    view_content_data_additional_information:
        items:
            orocrm_case_ticket_info: ~

items:
    orocrm_case_ticket_info:
        template: OroCRMZendeskBundle:Ticket:caseTicketInfo.html.twig
        applicable: @orocrm_zendesk.placeholder.filter->filter($entity$)
