parameters:
    orocrm_zendesk.entity.user.class:                         OroCRM\Bundle\ZendeskBundle\Entity\User
    orocrm_zendesk.entity.ticket.class:                       OroCRM\Bundle\ZendeskBundle\Entity\Ticket
    orocrm_zendesk.entity.ticket_comment.class:               OroCRM\Bundle\ZendeskBundle\Entity\TicketComment
    orocrm_zendesk.configuration_provider.class:              OroCRM\Bundle\ZendeskBundle\Provider\ConfigurationProvider
    orocrm_zendesk.entity_mapper.class:                       OroCRM\Bundle\ZendeskBundle\Model\EntityMapper
    orocrm_zendesk.rest_client_factory.class:                 OroCRM\Bundle\ZendeskBundle\Model\RestClientFactory
    orocrm_zendesk.twig.extension.case_ticket.class:          OroCRM\Bundle\ZendeskBundle\Twig\CaseTicketExtension
    orocrm_zendesk.twig.extension.ticket_path.class:          OroCRM\Bundle\ZendeskBundle\Twig\TicketPathExtension
    orocrm_zendesk.placeholder.filter.class:                  OroCRM\Bundle\ZendeskBundle\Placeholder\Filter\Filter
    orocrm_zendesk.sync_state_manager.class:                  OroCRM\Bundle\ZendeskBundle\Model\SyncStateManager
    orocrm_zendesk.sync_state.class:                          OroCRM\Bundle\ZendeskBundle\Model\SyncState

    # Integration related parameters
    orocrm_zendesk.form.type.rest_transport_setting.class:    OroCRM\Bundle\ZendeskBundle\Form\Type\RestTransportSettingsFormType
    orocrm_zendesk.transport.rest_transport.class:            OroCRM\Bundle\ZendeskBundle\Provider\Transport\Rest\ZendeskRestTransport

services:
    orocrm_zendesk.entity_mapper:
        class: %orocrm_zendesk.entity_mapper.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %orocrm_zendesk.map%

    orocrm_zendesk.configuration_provider:
        class: %orocrm_zendesk.configuration_provider.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_config.global

    orocrm_zendesk.rest_client_factory:
        class: %orocrm_zendesk.rest_client_factory.class%
        arguments:
            - @orocrm_zendesk.configuration_provider

    orocrm_zendesk.twig.extension.case_ticket:
        class: %orocrm_zendesk.twig.extension.case_ticket.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    orocrm_zendesk.twig.extension.ticket_path:
        class: %orocrm_zendesk.twig.extension.ticket_path.class%
        arguments:
            - @orocrm_zendesk.configuration_provider
        tags:
            - { name: twig.extension }

    orocrm_zendesk.placeholder.filter:
        class: %orocrm_zendesk.placeholder.filter.class%
        arguments:
            - @doctrine.orm.entity_manager

    orocrm_zendesk.sync_state_manager:
        class: %orocrm_zendesk.sync_state_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    orocrm_zendesk.sync_state:
        class: %orocrm_zendesk.sync_state.class%
        arguments:
            - @doctrine.orm.entity_manager

    # Integration related services
    orocrm_zendesk.form.type.rest_transport_setting:
        class: %orocrm_zendesk.form.type.rest_transport_setting.class%
        tags:
            - { name: form.type, alias: orocrm_zendesk_rest_transport_setting_form_type }

    orocrm_zendesk.transport.rest_transport:
        class: %orocrm_zendesk.transport.rest_transport.class%
        parent: oro_integration.transport.rest.abstract_transport
        tags:
            - { name: oro_integration.transport, type: zendesk_rest, channel_type: zendesk }
