parameters:
    orocrm_zendesk.entity.user.class:                          OroCRM\Bundle\ZendeskBundle\Entity\User
    orocrm_zendesk.provider.type.configuration_provider.class: OroCRM\Bundle\ZendeskBundle\Provider\ConfigurationProvider
    orocrm_zendesk.mapper.class:                               OroCRM\Bundle\ZendeskBundle\Model\Mapper
    orocrm_zendesk.rest_client_factory.class:                  OroCRM\Bundle\ZendeskBundle\Model\RestClientFactory

services:
    orocrm_zendesk.mapper:
        class: %orocrm_zendesk.mapper.class%
        arguments:
            - %orocrm_zendesk.map%

    orocrm_zendesk.provider.type.configuration_provider:
        class: %orocrm_zendesk.provider.type.configuration_provider.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_config.global

    orocrm_zendesk.rest_client_factory:
        class: %orocrm_zendesk.rest_client_factory.class%
        arguments:
            - @orocrm_zendesk.provider.type.configuration_provider
