parameters:
    orocrm_zendesk.entity.user.class:                          OroCRM\Bundle\ZendeskBundle\Entity\User
    orocrm_zendesk.entity.ticket.class:                        OroCRM\Bundle\ZendeskBundle\Entity\Ticket
    orocrm_zendesk.entity.ticket_comment.class:                OroCRM\Bundle\ZendeskBundle\Entity\TicketComment
    orocrm_zendesk.configuration_provider.class:               OroCRM\Bundle\ZendeskBundle\Provider\ConfigurationProvider
    orocrm_zendesk.entity_mapper.class:                        OroCRM\Bundle\ZendeskBundle\Model\EntityMapper
    orocrm_zendesk.rest_client_factory.class:                  OroCRM\Bundle\ZendeskBundle\Model\RestClientFactory
    orocrm_zendesk.twig.extension.case_ticket.class:           OroCRM\Bundle\ZendeskBundle\Twig\CaseTicketExtension
    orocrm_zendesk.twig.extension.ticket_path.class:           OroCRM\Bundle\ZendeskBundle\Twig\TicketPathExtension
    orocrm_zendesk.placeholder.filter.class:                   OroCRM\Bundle\ZendeskBundle\Placeholder\Filter\Filter
    orocrm_zendesk.sync_state_manager.class:                   OroCRM\Bundle\ZendeskBundle\Model\SyncStateManager

services:
    orocrm_zendesk.entity_mapper:
        class: %orocrm_zendesk.entity_mapper.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %orocrm_zendesk.map%

    orocrm_zendesk.configuration_provider:
        class: %orocrm_zendesk.configuration_provider.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_config.global

    orocrm_zendesk.rest_client_factory:
        class: %orocrm_zendesk.rest_client_factory.class%
        arguments:
            - @orocrm_zendesk.configuration_provider

    orocrm_zendesk.twig.extension.case_ticket:
        class: %orocrm_zendesk.twig.extension.case_ticket.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    orocrm_zendesk.twig.extension.ticket_path:
        class: %orocrm_zendesk.twig.extension.ticket_path.class%
        arguments:
            - @orocrm_zendesk.configuration_provider
        tags:
            - { name: twig.extension }

    orocrm_zendesk.placeholder.filter:
        class: %orocrm_zendesk.placeholder.filter.class%
        arguments:
            - @doctrine.orm.entity_manager

    orocrm_zendesk.sync_state_manager:
        class: %orocrm_zendesk.sync_state_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
