parameters:
    orocrm_zendesk.entity.user.class:                         OroCRM\Bundle\ZendeskBundle\Entity\User
    orocrm_zendesk.entity.ticket.class:                       OroCRM\Bundle\ZendeskBundle\Entity\Ticket
    orocrm_zendesk.entity.ticket_comment.class:               OroCRM\Bundle\ZendeskBundle\Entity\TicketComment
    orocrm_zendesk.entity_mapper.class:                       OroCRM\Bundle\ZendeskBundle\Model\EntityMapper
    orocrm_zendesk.twig.extension.case_ticket.class:          OroCRM\Bundle\ZendeskBundle\Twig\CaseTicketExtension
    orocrm_zendesk.twig.extension.ticket_path.class:          OroCRM\Bundle\ZendeskBundle\Twig\TicketPathExtension
    orocrm_zendesk.placeholder.filter.class:                  OroCRM\Bundle\ZendeskBundle\Placeholder\Filter\Filter
    orocrm_zendesk.sync_state.class:                          OroCRM\Bundle\ZendeskBundle\Model\SyncState

    # Integration related parameters
    orocrm_zendesk.form.type.rest_transport_setting.class:    OroCRM\Bundle\ZendeskBundle\Form\Type\RestTransportSettingsFormType
    orocrm_zendesk.form.sync_with_zendesk_extension.class:    OroCRM\Bundle\ZendeskBundle\Form\Extension\SyncWithZendeskExtension
    orocrm_zendesk.transport.rest_transport.class:            OroCRM\Bundle\ZendeskBundle\Provider\Transport\Rest\ZendeskRestTransport
    orocrm_zendesk.event_listener.case_form_handled.class:    OroCRM\Bundle\ZendeskBundle\EventListener\CaseEntity\CaseFormHandled
    orocrm_zendesk.model.sync_manager.class:                  OroCRM\Bundle\ZendeskBundle\Model\SyncManager

    # Listeners
    orocrm_zendesk.listener.doctrine.sync_update_case.class:  OroCRM\Bundle\ZendeskBundle\EventListener\Doctrine\SyncUpdateCaseListener

services:
    orocrm_zendesk.entity_mapper:
        class: %orocrm_zendesk.entity_mapper.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %orocrm_zendesk.map%

    orocrm_zendesk.twig.extension.case_ticket:
        class: %orocrm_zendesk.twig.extension.case_ticket.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

    orocrm_zendesk.twig.extension.ticket_path:
        class: %orocrm_zendesk.twig.extension.ticket_path.class%
        tags:
            - { name: twig.extension }

    orocrm_zendesk.placeholder.filter:
        class: %orocrm_zendesk.placeholder.filter.class%
        arguments:
            - @doctrine.orm.entity_manager

    orocrm_zendesk.sync_state:
        class: %orocrm_zendesk.sync_state.class%
        arguments:
            - @doctrine.orm.entity_manager

    # Integration related services
    orocrm_zendesk.form.type.rest_transport_setting:
        class: %orocrm_zendesk.form.type.rest_transport_setting.class%
        tags:
            - { name: form.type, alias: orocrm_zendesk_rest_transport_setting_form_type }

    orocrm_zendesk.form.sync_with_zendesk_extension:
        class: %orocrm_zendesk.form.sync_with_zendesk_extension.class%
        arguments:
            - @orocrm_zendesk.importexport.provider.zendesk_entity
            - @orocrm_zendesk.importexport.provider.oro_entity
        tags:
            - { name: form.type_extension, alias: orocrm_case_entity }

    orocrm_zendesk.event_listener.case_form_handled:
        class: %orocrm_zendesk.event_listener.case_form_handled.class%
        arguments:
            - @orocrm_zendesk.model.sync_manager
            - @orocrm_zendesk.importexport.provider.oro_entity
        tags:
            - { name: kernel.event_listener, event: orcrm_case.form_handler_on_success, method: onSuccess }

    orocrm_zendesk.transport.rest_transport:
        class: %orocrm_zendesk.transport.rest_transport.class%
        parent: oro_integration.transport.rest.abstract_transport
        tags:
            - { name: oro_integration.transport, type: zendesk_rest, channel_type: zendesk }

    orocrm_zendesk.model.sync_manager:
        class: %orocrm_zendesk.model.sync_manager.class%
        arguments:
            - @oro_integration.sync_scheduler
            - @doctrine.orm.entity_manager
            - @orocrm_zendesk.importexport.provider.zendesk_entity

    # Listeners
    orocrm_zendesk.listener.doctrine.sync_abstract:
        abstract: true
        arguments:
            - @oro_security.security_facade.link
            - @oro_integration.sync_scheduler.link

    orocrm_zendesk.listener.doctrine.sync_update_case:
        parent: orocrm_zendesk.listener.doctrine.sync_abstract
        class: %orocrm_zendesk.listener.doctrine.sync_update_case.class%
        tags:
            - { name: doctrine.event_subscriber }
