oro_system_configuration:
    groups:
        integrations:
            title: orocrm.zendesk.system_configuration.integrations.title

        zendesk_integration:
            title: orocrm.zendesk.system_configuration.zendesk_integration.title
            icon:  'icon-gear'

        zendesk_settings:
            title: orocrm.zendesk.system_configuration.zendesk_settings.title

    fields:
        oro_crm_zendesk.zendesk_email:
            type: email
            priority: 10
            options:
                label: orocrm.zendesk.form.email.label
                tooltip: orocrm.zendesk.form.email.tooltip
                required: true
                resettable: false
                constraints:
                    - NotBlank: ~
                    - Email: ~

        oro_crm_zendesk.zendesk_api_token:
            type: text
            priority: 9
            options:
                label: orocrm.zendesk.form.api_token.label
                tooltip: orocrm.zendesk.form.api_token.tooltip
                required: true
                resettable: false
                constraints:
                    - NotBlank: ~

        oro_crm_zendesk.zendesk_sync_timeout:
            type: number
            priority: 8
            options:
                label: orocrm.zendesk.form.sync_timeout.label
                tooltip: orocrm.zendesk.form.sync_timeout.tooltip
                required: true
                constraints:
                    - NotBlank: ~

        oro_crm_zendesk.zendesk_subdomain:
            type: text
            priority: 11
            options:
                label: orocrm.zendesk.form.subdomain.label
                tooltip: orocrm.zendesk.form.subdomain.tooltip
                required: true
                resettable: false
                constraints:
                    - NotBlank: ~

        oro_crm_zendesk.zendesk_default_user_email:
            type: text
            priority: 7
            options:
                label: orocrm.zendesk.form.zendesk_default_user_email.label
                tooltip: orocrm.zendesk.form.zendesk_default_user_email.tooltip
                required: true
                resettable: false
                constraints:
                    - NotBlank: ~

        oro_crm_zendesk.orocrm_default_username:
            type: text
            priority: 6
            options:
                label: orocrm.zendesk.form.default_username.label
                tooltip: orocrm.zendesk.form.default_username.tooltip
                required: true
                resettable: false
                constraints:
                    - NotBlank: ~

    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        priority: 255
                        children:
                            zendesk_integration:
                                priority: 255
                                children:
                                    zendesk_settings:
                                        children:
                                            - oro_crm_zendesk.zendesk_email
                                            - oro_crm_zendesk.zendesk_api_token
                                            - oro_crm_zendesk.zendesk_default_user_email
                                            - oro_crm_zendesk.orocrm_default_username
                                            - oro_crm_zendesk.zendesk_sync_timeout
                                            - oro_crm_zendesk.zendesk_subdomain
