oro_entity:
    entity_aliases:
        OroCRM\Bundle\ZendeskBundle\Entity\Ticket:
            alias:        zendeskticket
            plural_alias: zendesktickets
        OroCRM\Bundle\ZendeskBundle\Entity\TicketComment:
            alias:        zendeskticketcomment
            plural_alias: zendeskticketcomments
        OroCRM\Bundle\ZendeskBundle\Entity\User:
            alias:        zendeskuser
            plural_alias: zendeskusers

    entity_alias_exclusions:
        - OroCRM\Bundle\ZendeskBundle\Entity\TicketPriority
        - OroCRM\Bundle\ZendeskBundle\Entity\TicketPriorityTranslation
        - OroCRM\Bundle\ZendeskBundle\Entity\TicketStatus
        - OroCRM\Bundle\ZendeskBundle\Entity\TicketStatusTranslation
        - OroCRM\Bundle\ZendeskBundle\Entity\TicketType
        - OroCRM\Bundle\ZendeskBundle\Entity\TicketTypeTranslation
        - OroCRM\Bundle\ZendeskBundle\Entity\UserRole
        - OroCRM\Bundle\ZendeskBundle\Entity\UserRoleTranslation
